### ISSUE TITLE
Placeholder parameter

### ISSUE THREAD

**Issue by adriandmitroca** [ruimgoncalves/vuejs-typeahead#1]
Hi @ruimgoncalves.

For the beginning - great work. Thanks for that. However, I came up with an idea that param for the placeholder is missing. What are you think about that?

If you want I could probably deliver specific PR for that.

**Comment by ruimgoncalves** [comment]
Hi @adriandmitroca 

Nice catch, defensively missed that, thanks for the heads up. 
I'm currently away from my work machine, so if you can, please make a PR, I'll merge it ASAP. If not I'll probably take care of it tomorrow. 
Thanks

**Comment by ruimgoncalves** [comment]
Hi @adriandmitroca 
Just added this to version 0.2.2.

Thanks
