### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by Zyles** [ruimgoncalves/vuejs-typeahead#2]
Hey.

Could you add priority support?

If you type "abc", items with more weight should show up higher.

Thanks.

**Comment by ruimgoncalves** [comment]
Hi Zyles

Could you please elaborate.

But it seams the functionality you are requesting should not be implemented in the component, but rather through some data adapter that manages filtering and priority.

**Comment by Zyles** [comment]
If you have two words for example:

apple
application

I want "application" to come first in the typeahead box at the top because it is more relevant.

You think the API should handle this sorting?

**Comment by ruimgoncalves** [comment]
This is a classical case of separation of concerns, the typeahead component should only care about how to render the data thrown at it.

You can choose to change the API to get the optimal output base on your relevant order logic, but if this is not too compute intensive I would do this calculations on the client, between the API response and the typeahead component, freeing the server from this overhead.

Here is a simple sort by length example.

``` javascript
getInfoData(query){
   this.$http.get('api/search', {q : query}).then(
       ({data})=>{
          this.items = data.sort((a, b) => b.length - a.length);
      },
      (err)=>{
         this.items = []
      });
}
```
